/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StreetLightService } from "../streetLight.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StreetLightCreateInput } from "./StreetLightCreateInput";
import { StreetLight } from "./StreetLight";
import { StreetLightFindManyArgs } from "./StreetLightFindManyArgs";
import { StreetLightWhereUniqueInput } from "./StreetLightWhereUniqueInput";
import { StreetLightUpdateInput } from "./StreetLightUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StreetLightControllerBase {
  constructor(
    protected readonly service: StreetLightService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StreetLight })
  @nestAccessControl.UseRoles({
    resource: "StreetLight",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStreetLight(
    @common.Body() data: StreetLightCreateInput
  ): Promise<StreetLight> {
    return await this.service.createStreetLight({
      data: data,
      select: {
        brightness: true,
        createdAt: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [StreetLight] })
  @ApiNestedQuery(StreetLightFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "StreetLight",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async streetLights(@common.Req() request: Request): Promise<StreetLight[]> {
    const args = plainToClass(StreetLightFindManyArgs, request.query);
    return this.service.streetLights({
      ...args,
      select: {
        brightness: true,
        createdAt: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StreetLight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StreetLight",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async streetLight(
    @common.Param() params: StreetLightWhereUniqueInput
  ): Promise<StreetLight | null> {
    const result = await this.service.streetLight({
      where: params,
      select: {
        brightness: true,
        createdAt: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StreetLight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StreetLight",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStreetLight(
    @common.Param() params: StreetLightWhereUniqueInput,
    @common.Body() data: StreetLightUpdateInput
  ): Promise<StreetLight | null> {
    try {
      return await this.service.updateStreetLight({
        where: params,
        data: data,
        select: {
          brightness: true,
          createdAt: true,
          id: true,
          location: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StreetLight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StreetLight",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStreetLight(
    @common.Param() params: StreetLightWhereUniqueInput
  ): Promise<StreetLight | null> {
    try {
      return await this.service.deleteStreetLight({
        where: params,
        select: {
          brightness: true,
          createdAt: true,
          id: true,
          location: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
